name: "Composite actions"
description: "Testing composite actions"
inputs:
  name:
    description: "Enter name..."
    required: false
    default: "test"
outputs:
  number:
    description: "output value"
    value: ${{ steps.git_out.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: print name
      run: |
        echo "Enter name is - ${{ inputs.name }}"
      shell: bash

    - name: print github_env variable value
      run: |
        echo "sum=15" >> "$GITHUB_ENV"
      shell: bash

    - name: print github_output variable value
      id: git_out
      run: |
        echo "result=30" >> "$GITHUB_OUTPUT"
      shell: bash
