name: "WAIT TIMER"
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: |
          echo "Test"
          
  build:
    needs: test
    runs-on: ubuntu-latest
    environment: pre-prod
    steps:
      - name: build
        run: |
          echo "build"
